name: try-build-image

on:
    pull_request:
        branches: [master]

jobs:
    build-docker-image:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Django Config
              run: echo "${{ secrets.CONFIG_FILE }}" >> config.py

            - name: Build Docker image
              run: docker build -t chiefnoob/mosoon:latest .
